### PR TITLE
(global):implement redux

### PR DESCRIPTION
**Pull request by Dr-Legend**

### CODE REVIEW

**Comment by Dr-Legend** [comment]
No reply from you!

**Comment by Dr-Legend** [comment]
@Chimbi  Check My PR

**Comment by Chimbi** [comment]
The user is been saved in the onSave function with the sentence: User savedUser = store.state.page1formState.toUser();
The save option of the form is not been used for this.

**Comment by Chimbi** [comment]
Use only the save option of the form and then save it to the object
User savedUser = vm.page1formState.toUser();
                                        print("Saved user: ${savedUser.toString()}");

**Comment by Dr-Legend** [comment]
@Chimbi  is your problem get solved? I haven't received any response from you

**Pull request merged**
